name: 'Setup SQLite environment'
description: 'This action will setup the SQLite distribution'
author: 'Claudio Corsi'
inputs:
  sqlite-version:  # id of input
    description: 'The version of SQLite that you want to install, example, 3.40.0'
    required: false
  sqlite-year: # id of input
    description: 'The year that the SQLite version was released, example, 2022'
    required: false
  sqlite-url-path:
    description: 'The url prefix to the SQLite download site without the year and version information, for example, https://www.sqlite.org/'
    required: false
    default: 'https://www.sqlite.org/'
outputs:
  cache-hit: # used to indicate if the requested sqlite installation referenced is already locally installed
    description: 'A boolean value to indicate if a cache was hit'
  sqlite-version: # useful whenever the sqlite-version was not set
    description: 'The installed SQLite version'
  sqlite-bin: # useful whenever one wants to copy the installed sqlite version
    description: 'The directory that the sqlite was installed'
runs:
  using: 'node16' # can this be node18
  main: 'dist/index.js' # installs the requested sqlite version
